#!/bin/sh

LOGFILE="/var/log/ws_server.log"

#start() {
#	printf "Starting websocket_server: "
#	start-stop-daemon -S -q -m -b -p /var/run/websocket_server.pid \
#		--exec /usr/bin/websocket_server -- >> $LOGFILE 2>&1
#	[ $? = 0 ] && echo "OK" || echo "FAIL"
#}

#stop() {
#	printf "Stopping websocket_server: "
#	start-stop-daemon -K -q -p /var/run/websocket_server.pid
#	[ $? = 0 ] && echo "OK" || echo "FAIL"
#}

start() {
	sleep 5 # wait_for_network
	printf "Starting WebSocket Server: "
	/usr/bin/ws_server & 2>&1
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping WebSocket Server: "
	killall ws_server
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
